### ISSUE TITLE
Repr issue when in VSCode debugger

### ISSUE THREAD

**Issue by zaccharieramzi** [xl0/lovely-jax#1]
I am using lovely-jax in order to debug some jax code using the vscode debugger.
When I am displaying an all-zeros tensor I get the following output:
```
DeviceArray[100, 100] n=10000 [38;2;127;127;127mall_zeros[0m
```

When in a regular python console, I get the correctly formatted output:
```
DeviceArray[10, 10] n=100 all_zeros
```

I am not sure where this might be coming from...

**Comment by xl0** [comment]
Hi! That you for letting me know! :two_hearts: 

I'm wrapping things with a `lovely-tensors` + `lovely-numpy` rewrok, and I will give some much-deserved love to `lovely-jax` in about a week!

I'm not entirely sure what's causing the issue. If you have PyTorch, could you try to reproduce the same behaviour with `lovely-pytorch`? Both libraries should be using the same method to repr the colours, and I'm not seeing the same issue with PyToprch.

You can disable colours via `lovely_jax.PRINT_OPTS=False` as a workaround.

**Comment by xl0** [comment]
My mistake, I'm seeing the same behaviour in the debugger with `lovely-tensors`

Looks like the VScode debugger can't handle ANSI colours, and it's a known issue.

I wonder if there is a way to detect that we are running inside a debugger and disable colours automatically. Will look into it!

**Comment by xl0** [comment]
@zaccharieramzi, I just pushed out a fix. If you'd like to give it a try, please `pip install lovely-jax=0.1.1-dev0`.

**Comment by zaccharieramzi** [comment]
all working!
