### ISSUE TITLE
Tensor shape for `rgb` function

### ISSUE THREAD

**Issue by pablo2909** [xl0/lovely-jax#3]
Hello,

Thanks a lot for this super useful package !

One small thing, there is a comment [here](https://github.com/xl0/lovely-jax/blob/4961c6ceb1e23638fe85a244ec4b18671c472130/lovely_jax/repr_rgb.py#L74) that says the shape of an array can be (C, H, W) or (H, W, C), right ? But if I try (C, H, W) I get an error. Is this intended ?

Thanks again
Best

**Comment by xl0** [comment]
Hi. Do you pass  `cl=False` (channel-last)? If yes, what's the error?

**Comment by pablo2909** [comment]
My bad I didn't notice this argument and it works when I do that. Thanks for the quick feedback :)
